trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 0 * * 1-5"  # 8 AM UTC, Mon–Fri
    displayName: Daily Midnight Build
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: '$(Pipeline.Workspace)/.m2/repository'
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      options: '-Dtest=FullRegressionSuite'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  # Optional: Stub for Azure AI/Applitools integration on failure
  - script: |
      echo "Running AI analysis for failed tests..."
      # TODO: Insert API call to your AI testing tool here
    displayName: 'Run AI Failure Analysis'
    condition: failed()

  # Optional: Notify Microsoft Teams on failure
  - script: |
      echo "Sending Teams notification for test failure..."
      # TODO: Replace with real Teams webhook curl command or use Logic App
    displayName: 'Notify Teams on Failure'
    condition: failed()
